/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
  'moveInDate' : IDL.Int,
  'roomType' : IDL.Text,
});
export const Room = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'price' : IDL.Int,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'review' : IDL.Text,
  'studentName' : IDL.Text,
  'rating' : IDL.Int,
  'course' : IDL.Text,
});

export const idlService = IDL.Service({
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
    'moveInDate' : IDL.Int,
    'roomType' : IDL.Text,
  });
  const Room = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'price' : IDL.Int,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'review' : IDL.Text,
    'studentName' : IDL.Text,
    'rating' : IDL.Int,
    'course' : IDL.Text,
  });
  
  return IDL.Service({
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };